### PR TITLE
Fix defaulting render texture size on Quest 2

### LINKED ISSUE #86: Default Texture Size "Default button" incorrect resolution on Oculus Quest 2
I was expecting the default button change the setting back to default on oculus quest 2 but it seems that it set a lower value than what is actually default.
(restarting the headset resets the Default Texture Size to it defaults which for me increases the clarity compared to using the default button)

### PR DESCRIPTION
**Pull request by gerryhernandez**
This makes SideQuest intelligently choose the correct resolution by detecting the target device model, `(Quest|Quest 2)`. This fixes #86.

### CODE REVIEW

**Comment by gerryhernandez** [comment]
I think the actual CI build configuration is broken, by the way. Same error as the other accepted PR. 🙂

**Comment by sidequestlegend** [comment]
I wonder could we leverage this section where we are already grabbing the quest 2 model 
https://github.com/SideQuestVR/SideQuest/blob/6162dbe601c0a4807529a6eafb69232fdb890eac/desktop-app/src/app/adb-client.service.ts#L316

**Comment by gerryhernandez** [comment]
I completely missed that. I agree; I’ll refactor it in a bit when I’m back at the computer.

**Comment by Slin** [comment]
While you are at it...
Default Quest 2 resolution is 1440 x 1584
Default Quest 1 resolution is 1216 x 1344
And as you can see these are both not square.
1024x1024 was the default resolution for Oculus Go, which your changes will fail completely.

I was gonna do it, but then I found this ;)

**Comment by gerryhernandez** [comment]
Sorry gentlemen, I was out of town for a while. I'll be able to clean this up and finish this tonight. Just to make sure we're being very precise, @Slin , where did you find those resolutions? And now you've made me realize that we need to properly support Oculus Go, so I'll need the `ro.product.model` string for it. I don't want to do it on assumption, so can we track this down to be sure?

**Comment by Slin** [comment]
The resolutions come from me putting a breakpoint into my own code that gets the resolutions from vrapi.
I also just confirmed it with the ovr metrics tool though. It stays the same independent of the lense position on quest 2.
`ro.product.model` on my Go is `Pacific`

**Comment by sidequestlegend** [comment]
Im going to close this since we added buttons for all defaults in a recent update.

**Pull request closed without merging**
